---
apiVersion: v1
kind: Service
metadata:
  name: gpt-hf-service
spec:
  type: ClusterIP   # NodePort for Minikube, ClusterIP for Ingress; ClusterIP is fine here
  selector:
    app: gpt-hf-pod
  ports:
    - port: 8000
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpt-hf-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: gpt.203.0.113.10.sslip.io   # put some example EXTERNAL-IP here
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gpt-hf-service
                port:
                  number: 8000